# Generated by Django 2.1.7 on 2019-03-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20190303_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedprogram',
            name='script',
            field=models.TextField(null=True),
        ),
    ]
